"""Remove isbn field

Revision ID: 83e816d53c0d
Revises: 6fa9297bc118
Create Date: 2024-10-29 00:22:08.254650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e816d53c0d'
down_revision = '6fa9297bc118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_isbn_key', 'books', type_='unique')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
    op.create_unique_constraint('books_isbn_key', 'books', ['isbn'])
    # ### end Alembic commands ###
