"""Make isbn optional in Book model

Revision ID: 917681bc47e2
Revises: b092b852779a
Create Date: 2024-10-29 12:38:56.279626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917681bc47e2'
down_revision = 'b092b852779a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
