"""Set default value for published_date in Book model

Revision ID: b092b852779a
Revises: 83e816d53c0d
Create Date: 2024-10-29 00:25:13.299244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b092b852779a'
down_revision = '83e816d53c0d'
branch_labels = None
depends_on = None


def upgrade():
    # Alter the published_date column to add server_default
    op.alter_column(
        'books', 
        'published_date',
        existing_type=sa.DATE(),
        nullable=False,
        server_default=sa.text('CURRENT_DATE')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'published_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


